[admin]
adm-ansible-01 ansible_connection=local

[dmz]
rp-traefik-01 ansible_host=10.10.10.10 node_role=reverse_proxy

[monitoring]
mon-grafana-01 ansible_host=10.10.20.20 node_role=monitoring

[docker_hosts]
app-docker-01 ansible_host=10.10.20.10 node_role=application

[logs]
log-loki-01 ansible_host=10.10.20.30 node_role=logs

[node_exporters]
app-docker-01 ansible_host=10.10.20.10
rp-traefik-01 ansible_host=10.10.10.10
mon-grafana-01 ansible_host=10.10.20.20



[all:vars]
ansible_user=ansible
