[admin]
adm-ansible-01 ansible_host=10.10.30.10

[dmz]
rp-traefik-01 ansible_host=10.10.10.10

[lan]
app-docker-01 ansible_host=10.10.20.10
mon-grafana-01 ansible_host=10.10.20.20
log-loki-01 ansible_host=10.10.20.30

[all:vars]
ansible_user=ansible
