- name: Ensure hostname is resolvable locally
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: Create Traefik directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /opt/traefik
    - /opt/traefik/config
    - /opt/traefik/certs

- name: Deploy TLS certificate
  copy:
    dest: /opt/traefik/certs/demo.lab.local.crt
    content: "{{ traefik_tls_cert }}"
    mode: '0644'

- name: Deploy TLS key
  copy:
    dest: /opt/traefik/certs/demo.lab.local.key
    content: "{{ traefik_tls_key }}"
    mode: '0600'


- name: Create Traefik docker-compose file
  copy:
    dest: /opt/traefik/docker-compose.yml
    owner: root
    group: root
    mode: "0644"
    content: |
      services:
        traefik:
          image: traefik:v3.6
          container_name: traefik
          restart: unless-stopped
          command:
            - "--api.dashboard=true"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.file.filename=/etc/traefik/dynamic.yml"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
          ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /opt/traefik/config/dynamic.yml:/etc/traefik/dynamic.yml:ro
            - /opt/traefik/certs:/certs:ro
    notify: Restart Traefik


- name: Create Traefik dynamic config
  copy:
    dest: /opt/traefik/config/dynamic.yml
    owner: root
    group: root
    mode: "0644"
    content: |
      http:
        routers:
          demo-app-http:
            rule: "Host(`demo.lab.local`)"
            entryPoints:
              - web
            middlewares:
              - redirect-to-https
            service: noop@internal

          demo-app:
            rule: "Host(`demo.lab.local`)"
            entryPoints:
              - websecure
            service: demo-app
            tls: {}

        middlewares:
          redirect-to-https:
            redirectScheme:
              scheme: https
              permanent: true

        services:
          demo-app:
            loadBalancer:
              servers:
                - url: "http://10.10.20.10:8081"

      tls:
        certificates:
          - certFile: "/certs/demo.lab.local.crt"
            keyFile: "/certs/demo.lab.local.key"
    notify: Restart Traefik



- name: Start Traefik stack
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: present
