- name: Configure Docker hosts
  hosts: docker_hosts
  become: true

  roles:
    - docker
    - demo_app

- name: Configure reverse proxy
  hosts: dmz
  become: true

  vars_files:
    - ../secrets/traefik/tls.yml

  roles:
    - docker
    - traefik

- name: Configure monitoring stack
  hosts: monitoring
  become: true

  roles:
    - docker
    - monitoring


- name: Deploy node exporter
  hosts: node_exporters
  become: true

  roles:
    - docker
    - node_exporter


- name: Configure logs stack
  hosts: logs
  become: true
  roles:
    - docker
    - loki

- name: Deploy promtail
  hosts: all
  become: true
  roles:
    - promtail

